name: docker-build-image-api

# Vérifie que le déclenchement provient de la branche main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - project-build

    steps:
      - uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Connect to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: package.jar

      # Juste pour le contrôle
      - name: List files in the repository
        run: ls ${{ github.workspace }}

      # Construction de l'image Docker et push sur DockerHub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/helloworld:latest

      - run: echo "This job's status is ${{ job.status }}."
